spring:
  profiles:
    active: prod
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate: org.hibernate.dialect.MariaDBDialect
        format_sql: true
    logging:
      level: 'org.hibernate.type.descriptor.sql: trace'
    thymeleaf:
      cache: false
    devtools:
      livereload:
        enabled: true
      restart:
        enabled: true

logging:
  level:
    org.hibernate.SQL: debug